apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-dropwizard
spec:
  replicas: 3
  selector:
    app: hello-dropwizard
  template:
    metadata:
      name: hello-dropwizard
      labels:
        app: hello-dropwizard
    spec:
      containers:
      - name: hello-dropwizard
        image: karthi102/hello1:19
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

